---
- name: nextcloud role
  tags:
    - nextcloud
  block:

  # assert
  - name: Assertions for nextcloud role
    ansible.builtin.assert:
      that:
      - nextcloud_db_pw != None
      - nextcloud_admin_user != None
      - nextcloud_admin_pw != None
      - nextcloud_config_template != None

  # apt
  - name: Apt install {{ nextcloud_apt_install }}
    become: true
    ansible.builtin.package:
      name: "{{ nextcloud_apt_install }}"
      state: present

  # download
  - name: Download the latest Nextcloud zip archive
    become: true
    ansible.builtin.get_url:
      url: "{{ nextcloud_opt_url }}"
      dest: /tmp/nextcloud-latest.zip
      mode: '0644'

  # mkdir
  - name: Mkdir {{ nextcloud_opt_dst }}
    become: true
    ansible.builtin.file:
      path: "{{ nextcloud_opt_dst }}"
      state: directory
      owner: "{{ nextcloud_linux_user }}"
      group: "{{ nextcloud_linux_user }}"
      mode: '0755'

  # unzip
  - name: Unzip Nextcloud archive
    become: true
    ansible.builtin.unarchive:
      src: /tmp/nextcloud-latest.zip
      dest: "{{ nextcloud_opt_dst | dirname }}"
      remote_src: true
      owner: "{{ nextcloud_linux_user }}"
      group: "{{ nextcloud_linux_user }}"
      creates: "{{ nextcloud_opt_dst | }}/config/config.php"

  # check
  - name: Check if Nextcloud is already installed
    become: true
    ansible.builtin.stat:
      path: "{{ nextcloud_opt_dst }}/config/config.php"
    register: __nextcloud_config_file

  # install
  - when: __nextcloud_config_file.stat.exists == false
    name: Run Nextcloud installation via occ command
    become: true
    become_user: www-data
    ansible.builtin.command:
      cmd: >
        php occ maintenance:install
        --database='mysql'
        --database-name="{{ nextcloud_db_name }}"
        --database-user="{{ nextcloud_db_user }}"
        --database-pass="{{ nextcloud_db_pw }}"
        --admin-user="{{ nextcloud_admin_user }}"
        --admin-pass="{{ nextcloud_admin_pw }}"
    args:
      chdir: "{{ nextcloud_opt_dst }}"
    no_log: true # Protects sensitive passwords from showing up in Ansible logs

  # config.php
  - name: Configure fpm at /etc/php/{{ php_version }}/fpm/php.ini
    ansible.builtin.lineinfile:
      path: "{{ nextcloud_opt_dst }}/config/config.php"
      regexp: "^;?\\s*{{ item.key | regexp_escape }}\\s*="
      line: "{{ item.key }} = {{ item.value }}"
      state: present
      owner: "{{ nextcloud_linux_user }}"
      group: "{{ nextcloud_linux_user }}"
      mode: u=rw,g=rw,o=
    loop: "{{ php_fpm_config_vars }}"
    notify: Restart PHP-FPM