---
- name: nextcloud role
  tags: [role-nextcloud]
  block:

  # install
  - ansible.builtin.import_tasks: subtasks/nextcloud-install.yml

  # init
  - ansible.builtin.import_tasks: subtasks/nextcloud-init.yml

  # config
  - ansible.builtin.import_tasks: subtasks/nextcloud-config-overrides.yml

  # systemd
  - ansible.builtin.import_tasks: subtasks/nextcloud-systemd.yml