---
- name: nextcloud role
  tags:
    - nextcloud
  block:

  # assert
  - name: Assertions for nextcloud role
    ansible.builtin.assert:
      that:
      - nextcloud_db_pw != None
      - nextcloud_admin_user != None
      - nextcloud_admin_pw != None
      - nextcloud_config_vars | length > 0
      - nextcloud_install_opt_dst != None
      - nextcloud_linux_user != None

  # check required packages
  - name: Check required packages
    ansible.builtin.package:
      state: present
      name:
      - php
    check_mode: true

  # apt
  - name: Apt install unzip sudo
    become: true
    ansible.builtin.package:
      state: present
      name:
      - unzip
      - sudo

  # install
  - ansible.builtin.import_tasks: install.yml

  # config
  - when: nextcloud_config_overrides | length > 0
    tags: [nextcloud-config]
    name: Template config overrides to {{ nextcloud_install_opt_dst }}/config/ansible_overrides.config.php
    ansible.builtin.template:
      src: ansible_overrides.config.php.j2
      dest: "{{ nextcloud_install_opt_dst }}/config/ansible_overrides.config.php"
      owner: "{{ nextcloud_linux_user }}"
      group: "{{ nextcloud_linux_user }}"
      mode: '0640'