---
- tags: [role-nextcloud-install]
  block:

  # assert
  - name: Assertions for nextcloud-install
    ansible.builtin.assert:
      that:
      - nextcloud_app_dir != None

  # absent
  - when: nextcloud_install_state == "absent"
    name: Remove {{ nextcloud_app_dir }}
    become: true
    ansible.builtin.file:
      path: "{{ nextcloud_app_dir }}"
      state: absent

  # present | reinstall
  - when: nextcloud_install_state == "present"
    block:

    # assert
    - name: Assertions for nextcloud-install
      ansible.builtin.assert:
        that:
        - nextcloud_linux_user != None
        - nextcloud_install_opt_url != None

    # check required packages
    - name: Check required packages
      ansible.builtin.package:
        state: present
        name:
        - php
      check_mode: true

    # apt
    - name: Apt install unzip sudo
      become: true
      ansible.builtin.package:
        state: present
        name:
        - unzip
        - sudo

    # mkdir
    - name: Mkdir {{ nextcloud_app_dir }}
      become: true
      ansible.builtin.file:
        path: "{{ nextcloud_app_dir }}"
        state: directory
        owner: "{{ nextcloud_linux_user }}"
        group: "{{ nextcloud_linux_user }}"
        mode: '0755'

    # download
    - name: Download the latest Nextcloud zip archive
      become: true
      ansible.builtin.get_url:
        url: "{{ nextcloud_install_opt_url }}"
        dest: /tmp/nextcloud-latest.zip
        mode: '0644'

    # unzip
    # extract only, will overwrite core files but not data
    - name: Unzip Nextcloud archive
      become: true
      ansible.builtin.unarchive:
        src: /tmp/nextcloud-latest.zip
        dest: "{{ nextcloud_app_dir | dirname }}"
        remote_src: true
        owner: "{{ nextcloud_linux_user }}"
        group: "{{ nextcloud_linux_user }}"
        creates: "{{ nextcloud_app_dir }}/config/config.php"