---
- tags: [role-nextcloud-config]
  block:

  # config
  - when: nextcloud_config_overrides | length > 0
    name: Template config overrides to {{ nextcloud_app_dir }}/config/ansible_overrides.config.php
    ansible.builtin.template:
      src: ansible_overrides.config.php.j2
      dest: "{{ nextcloud_app_dir }}/config/ansible_overrides.config.php"
      owner: "{{ nextcloud_linux_user }}"
      group: "{{ nextcloud_linux_user }}"
      mode: '0640'