---
- tags: [role-nextcloud-init]
  block:

  # assert
  - name: Assertions for nextcloud-init
    ansible.builtin.assert:
      that:
      - nextcloud_app_dir != None
      - nextcloud_data_dir != None
      - nextcloud_db_pw != None
      - nextcloud_admin_user != None
      - nextcloud_admin_pw != None
      - nextcloud_linux_user != None

  # check
  - name: Check if Nextcloud is already installed
    become: true
    ansible.builtin.stat:
      path: "{{ nextcloud_app_dir }}/config/config.php"
    register: __nextcloud_config_file

  # install
  # required to initialize the database
  # first time only
  - when: __nextcloud_config_file.stat.exists == false
    name: Run Nextcloud installation via occ command
    become: true
    become_user: "{{ nextcloud_linux_user }}"
    environment:
      ansible_remote_tmp: /tmp
    no_log: false
    args:
      chdir: "{{ nextcloud_app_dir }}"
    ansible.builtin.command:
      cmd: >
        php occ maintenance:install
        --database='mysql'
        --database-name="{{ nextcloud_db_name }}"
        --database-user="{{ nextcloud_db_user }}"
        --database-pass="{{ nextcloud_db_pw }}"
        --data-dir="{{ nextcloud_data_dir }}"
        --admin-user="{{ nextcloud_admin_user }}"
        --admin-pass="{{ nextcloud_admin_pw }}"